import { TILE_URL, TILE_ATTRIBUTION, MILES_TO_METERS } from './constants';

export function generateEmbedCode({ center, zones, singleZone, drawingMode: _drawingMode }) {
  const allZones = zones.length > 0 ? zones : singleZone ? [singleZone] : [];

  if (!center || allZones.length === 0) return '';

  const zoneJS = allZones.map((zone) => {
    if (zone.type === 'radius' || zone.radius) {
      const radiusMeters = (zone.radius || 15) * MILES_TO_METERS;
      return `
    L.circle([${center.lat}, ${center.lng}], {
      radius: ${radiusMeters.toFixed(0)},
      color: '${zone.color || '#0073EC'}',
      fillColor: '${zone.color || '#0073EC'}',
      fillOpacity: ${zone.opacity || 0.2},
      weight: ${zone.borderWidth || 2}
    }).addTo(map)${zone.name ? `.bindPopup('${zone.name.replace(/'/g, "\\'")}')` : ''};`;
    } else if (zone.points && zone.points.length >= 3) {
      const latlngs = zone.points.map(p => `[${p[0]}, ${p[1]}]`).join(', ');
      return `
    L.polygon([${latlngs}], {
      color: '${zone.color || '#0073EC'}',
      fillColor: '${zone.color || '#0073EC'}',
      fillOpacity: ${zone.opacity || 0.2},
      weight: ${zone.borderWidth || 2}
    }).addTo(map)${zone.name ? `.bindPopup('${zone.name.replace(/'/g, "\\'")}')` : ''};`;
    }
    return '';
  }).filter(Boolean).join('\n');

  return `<!-- Service Area Map - Generated by DreamHost Free Tools -->
<div id="service-area-map" style="width:100%;min-height:400px;border-radius:12px;overflow:hidden;"></div>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<script>
(function() {
  var map = L.map('service-area-map').setView([${center.lat}, ${center.lng}], 11);
  L.tileLayer('${TILE_URL}', {
    attribution: '${TILE_ATTRIBUTION}',
    maxZoom: 19
  }).addTo(map);

  L.marker([${center.lat}, ${center.lng}]).addTo(map);
${zoneJS}
})();
</script>`;
}
